export const AppErrorCodes = {
  USER_ALREADY_EXISTS:"USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS:"INVALID_CREDENTIALS",
  ACCOUNT_BLOCKED:"ACCOUNT_BLOCKED",
  EMAIL_INVALID:"EMAIL_INVALID",
  PASSWORD_INVALID:"PASSWORD_INVALID",
  SESSION_EXPIRED:"SESSION_EXPIRED",
} as const;

export type AppErrorCodesType = typeof AppErrorCodes[keyof typeof AppErrorCodes];
