export const AppErrorCodes = {
  USER_ALREADY_EXISTS:"USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS:"INVALID_CREDENTIALS",
  ACCOUNT_BLOCKED:"ACCOUNT_BLOCKED",
  EMAIL_INVALID:"EMAIL_INVALID",
  PASSWORD_INVALID:"PASSWORD_INVALID",
  SESSION_EXPIRED:"SESSION_EXPIRED",
  INTERNAL_SERVER_ERROR:"INTERNAL_SERVER_ERROR",
  INVALID_INPUT:"INVALID_INPUT",
  FILE_NOT_FOUND:"FILE_NOT_FOUND",
  FILE_INVALID:"FILE_INVALID",
  IMAGE_KYC_COMPLETED:"IMAGE_KYC_COMPLETED",
  VIDEO_KYC_COMPLETED:"VIDEO_KYC_COMPLETED",
  USER_NOT_FOUND:"ACCOUNT_NOT_FOUND",
} as const;

export type AppErrorCodesType = typeof AppErrorCodes[keyof typeof AppErrorCodes];
